# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/ktouch/w700/setup-makefiles.sh

# Audio
PRODUCT_COPY_FILES += \
    vendor/ktouch/w700/proprietary/lib/libaudio.so:obj/lib/libaudio.so \
    vendor/ktouch/w700/proprietary/lib/libaudiopolicy.so:obj/lib/libaudiopolicy.so \
    vendor/ktouch/w700/proprietary/lib/liba2dp.so:system/lib/liba2dp.so \
    vendor/ktouch/w700/proprietary/lib/libasound.so:system/lib/libasound.so \
    vendor/ktouch/w700/proprietary/lib/libaudio.so:system/lib/libaudio.so \
    vendor/ktouch/w700/proprietary/lib/libaudiopolicy.so:system/lib/libaudiopolicy.so \
    vendor/ktouch/w700/proprietary/etc/asound.conf:system/etc/asound.conf

# Camera
PRODUCT_COPY_FILES += \
    vendor/ktouch/w700/proprietary/lib/libcamera.so:obj/lib/libcamera.so \
    vendor/ktouch/w700/proprietary/lib/libcamera.so:system/lib/libcamera.so \
    vendor/ktouch/w700/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
    vendor/ktouch/w700/proprietary/lib/libcameraservice.so:system/lib/libcameraservice.so

# ALSA
PRODUCT_COPY_FILES += \
    vendor/ktouch/w700/proprietary/usr/share/alsa/alsa.conf:system/usr/share/alsa/alsa.conf \
    vendor/ktouch/w700/proprietary/usr/share/alsa/cards/aliases.conf:system/usr/share/alsa/cards/aliases.conf \
    vendor/ktouch/w700/proprietary/usr/share/alsa/pcm/center_lfe.conf:system/usr/share/alsa/pcm/center_lfe.conf \
    vendor/ktouch/w700/proprietary/usr/share/alsa/pcm/dpl.conf:system/usr/share/alsa/pcm/dpl.conf \
    vendor/ktouch/w700/proprietary/usr/share/alsa/pcm/iec958.conf:system/usr/share/alsa/pcm/iec958.conf \
    vendor/ktouch/w700/proprietary/usr/share/alsa/pcm/side.conf:system/usr/share/alsa/pcm/side.conf \
    vendor/ktouch/w700/proprietary/usr/share/alsa/pcm/default.conf:system/usr/share/alsa/pcm/default.conf \
    vendor/ktouch/w700/proprietary/usr/share/alsa/pcm/dsnoop.conf:system/usr/share/alsa/pcm/dsnoop.conf \
    vendor/ktouch/w700/proprietary/usr/share/alsa/pcm/modem.conf:system/usr/share/alsa/pcm/modem.conf \
    vendor/ktouch/w700/proprietary/usr/share/alsa/pcm/surround40.conf:system/usr/share/alsa/pcm/surround40.conf \
    vendor/ktouch/w700/proprietary/usr/share/alsa/pcm/surround41.conf:system/usr/share/alsa/pcm/surround41.conf \
    vendor/ktouch/w700/proprietary/usr/share/alsa/pcm/surround50.conf:system/usr/share/alsa/pcm/surround50.conf \
    vendor/ktouch/w700/proprietary/usr/share/alsa/pcm/surround51.conf:system/usr/share/alsa/pcm/surround51.conf \
    vendor/ktouch/w700/proprietary/usr/share/alsa/pcm/surround71.conf:system/usr/share/alsa/pcm/surround71.conf \
    vendor/ktouch/w700/proprietary/usr/share/alsa/pcm/dmix.conf:system/usr/share/alsa/pcm/dmix.conf \
    vendor/ktouch/w700/proprietary/usr/share/alsa/pcm/front.conf:system/usr/share/alsa/pcm/front.conf \
    vendor/ktouch/w700/proprietary/usr/share/alsa/pcm/rear.conf:system/usr/share/alsa/pcm/rear.conf

# HAL
PRODUCT_COPY_FILES += \
    vendor/ktouch/w700/proprietary/lib/hw/gralloc.tegra.so:system/lib/hw/gralloc.tegra.so \
    vendor/ktouch/w700/proprietary/lib/hw/overlay.tegra.so:system/lib/hw/overlay.tegra.so \
    vendor/ktouch/w700/proprietary/lib/hw/sensors.whistler.so:system/lib/hw/sensors.whistler.so \
    vendor/ktouch/w700/proprietary/lib/hw/tegra_alsa.tegra.so:system/lib/hw/tegra_alsa.tegra.so \
    vendor/ktouch/w700/proprietary/lib/hw/gps.tegra.so:system/lib/hw/gps.tegra.so \
    vendor/ktouch/w700/proprietary/lib/hw/lights.whistler.so:system/lib/hw/lights.whistler.so

# EGL
PRODUCT_COPY_FILES += \
    vendor/ktouch/w700/proprietary/lib/egl/libEGL_tegra.so:system/lib/egl/libEGL_tegra.so \
    vendor/ktouch/w700/proprietary/lib/egl/libGLESv1_CM_tegra.so:system/lib/egl/libGLESv1_CM_tegra.so \
    vendor/ktouch/w700/proprietary/lib/egl/libGLESv2_tegra.so:system/lib/egl/libGLESv2_tegra.so

# Wifi
PRODUCT_COPY_FILES += \
    vendor/ktouch/w700/proprietary/etc/firmware/nvram.txt:system/etc/firmware/nvram.txt \
    vendor/ktouch/w700/proprietary/etc/firmware/fw_bcmwlan_apsta.bin:system/etc/firmware/fw_bcmwlan_apsta.bin \
    vendor/ktouch/w700/proprietary/etc/firmware/fw_bcmwlan.bin:system/etc/firmware/fw_bcmwlan.bin

#keyboard files
PRODUCT_COPY_FILES += \
    vendor/ktouch/w700/proprietary/usr/keychars/qwerty.kcm.bin:system/usr/keychars/qwerty.kcm.bin \
    vendor/ktouch/w700/proprietary/usr/keychars/qwerty2.kcm.bin:system/usr/keychars/qwerty2.kcm.bin \
    vendor/ktouch/w700/proprietary/usr/keylayout/AVRCP.kl:system/usr/keylayout/AVRCP.kl \
    vendor/ktouch/w700/proprietary/usr/keylayout/gpio-keys.kl:system/usr/keylayout/gpio-keys.kl \
    vendor/ktouch/w700/proprietary/usr/keylayout/qwerty.kl:system/usr/keylayout/qwerty.kl

# Firmware
PRODUCT_COPY_FILES += \
    vendor/ktouch/w700/proprietary/etc/firmware/nvddk_audiofx_core.axf:system/etc/firmware/nvddk_audiofx_core.axf \
    vendor/ktouch/w700/proprietary/etc/firmware/nvddk_audiofx_transport.axf:system/etc/firmware/nvddk_audiofx_transport.axf \
    vendor/ktouch/w700/proprietary/etc/firmware/nvmm_aacdec.axf:system/etc/firmware/nvmm_aacdec.axf \
    vendor/ktouch/w700/proprietary/etc/firmware/nvmm_adtsdec.axf:system/etc/firmware/nvmm_adtsdec.axf \
    vendor/ktouch/w700/proprietary/etc/firmware/nvmm_mp3dec.axf:system/etc/firmware/nvmm_mp3dec.axf \
    vendor/ktouch/w700/proprietary/etc/firmware/nvmm_mpeg4dec.axf:system/etc/firmware/nvmm_mpeg4dec.axf \
    vendor/ktouch/w700/proprietary/etc/firmware/nvmm_audiomixer.axf:system/etc/firmware/nvmm_audiomixer.axf \
    vendor/ktouch/w700/proprietary/etc/firmware/nvmm_h264dec.axf:system/etc/firmware/nvmm_h264dec.axf \
    vendor/ktouch/w700/proprietary/etc/firmware/nvmm_jpegdec.axf:system/etc/firmware/nvmm_jpegdec.axf \
    vendor/ktouch/w700/proprietary/etc/firmware/nvmm_jpegenc.axf:system/etc/firmware/nvmm_jpegenc.axf \
    vendor/ktouch/w700/proprietary/etc/firmware/nvmm_manager.axf:system/etc/firmware/nvmm_manager.axf \
    vendor/ktouch/w700/proprietary/etc/firmware/nvmm_mp2dec.axf:system/etc/firmware/nvmm_mp2dec.axf \
    vendor/ktouch/w700/proprietary/etc/firmware/nvmm_reference.axf:system/etc/firmware/nvmm_reference.axf \
    vendor/ktouch/w700/proprietary/etc/firmware/nvmm_service.axf:system/etc/firmware/nvmm_service.axf \
    vendor/ktouch/w700/proprietary/etc/firmware/nvmm_sorensondec.axf:system/etc/firmware/nvmm_sorensondec.axf \
    vendor/ktouch/w700/proprietary/etc/firmware/nvmm_wavdec.axf:system/etc/firmware/nvmm_wavdec.axf \
    vendor/ktouch/w700/proprietary/etc/firmware/nvrm_avp.bin:system/etc/firmware/nvrm_avp.bin

# GPS
PRODUCT_COPY_FILES += \
    vendor/ktouch/w700/proprietary/etc/firmware/glconfig.xml:system/etc/firmware/glconfig.xml \
    vendor/ktouch/w700/proprietary/etc/firmware/cacert.pem:system/etc/firmware/cacert.pem \
    vendor/ktouch/w700/proprietary/bin/glgps:system/bin/glgps

# Sensor
PRODUCT_COPY_FILES += \
    vendor/ktouch/w700/proprietary/bin/akmd8975:system/bin/akmd8975 \
    vendor/ktouch/w700/proprietary/lib/libmlplatform.so:system/lib/libmlplatform.so \
    vendor/ktouch/w700/proprietary/lib/libmpl.so:system/lib/libmpl.so \
    vendor/ktouch/w700/proprietary/lib/libsensors.mpl.so:system/lib/libsensors.mpl.so \
    vendor/ktouch/w700/proprietary/lib/libmllite.so:system/lib/libmllite.so

# Firmware
PRODUCT_COPY_FILES += \
    vendor/ktouch/w700/proprietary/etc/firmware/bcm4329.hcd:system/etc/firmware/bcm4329.hcd \
    vendor/ktouch/w700/proprietary/etc/firmware/brcm_bluetooth.hcd:system/etc/firmware/brcm_bluetooth.hcd

# NV Libs
PRODUCT_COPY_FILES += \
    vendor/ktouch/w700/proprietary/lib/libardrv_dynamic.so:system/lib/libardrv_dynamic.so \
    vendor/ktouch/w700/proprietary/lib/libcgdrv.so:system/lib/libcgdrv.so \
    vendor/ktouch/w700/proprietary/lib/libnvddk_2d.so:system/lib/libnvddk_2d.so \
    vendor/ktouch/w700/proprietary/lib/libnvddk_2d_v2.so:system/lib/libnvddk_2d_v2.so \
    vendor/ktouch/w700/proprietary/lib/libnvddk_aes_user.so:system/lib/libnvddk_aes_user.so \
    vendor/ktouch/w700/proprietary/lib/libnvddk_audiofx.so:system/lib/libnvddk_audiofx.so \
    vendor/ktouch/w700/proprietary/lib/libnvddk_vmr.so:system/lib/libnvddk_vmr.so \
    vendor/ktouch/w700/proprietary/lib/libnvdispmgr_d.so:system/lib/libnvdispmgr_d.so \
    vendor/ktouch/w700/proprietary/lib/libnvec.so:system/lib/libnvec.so \
    vendor/ktouch/w700/proprietary/lib/libnvmm_audio.so:system/lib/libnvmm_audio.so \
    vendor/ktouch/w700/proprietary/lib/libnvmm_camera.so:system/lib/libnvmm_camera.so \
    vendor/ktouch/w700/proprietary/lib/libnvmm_contentpipe.so:system/lib/libnvmm_contentpipe.so \
    vendor/ktouch/w700/proprietary/lib/libnvmm_image.so:system/lib/libnvmm_image.so \
    vendor/ktouch/w700/proprietary/lib/libnvmm_manager.so:system/lib/libnvmm_manager.so \
    vendor/ktouch/w700/proprietary/lib/libnvmm_misc.so:system/lib/libnvmm_misc.so \
    vendor/ktouch/w700/proprietary/lib/libnvmm_parser.so:system/lib/libnvmm_parser.so \
    vendor/ktouch/w700/proprietary/lib/libnvmm_service.so:system/lib/libnvmm_service.so \
    vendor/ktouch/w700/proprietary/lib/libnvmm.so:system/lib/libnvmm.so \
    vendor/ktouch/w700/proprietary/lib/libnvmm_tracklist.so:system/lib/libnvmm_tracklist.so \
    vendor/ktouch/w700/proprietary/lib/libnvmm_utils.so:system/lib/libnvmm_utils.so \
    vendor/ktouch/w700/proprietary/lib/libnvmm_videorenderer.so:system/lib/libnvmm_videorenderer.so \
    vendor/ktouch/w700/proprietary/lib/libnvmm_video.so:system/lib/libnvmm_video.so \
    vendor/ktouch/w700/proprietary/lib/libnvmm_vp6_video.so:system/lib/libnvmm_vp6_video.so \
    vendor/ktouch/w700/proprietary/lib/libnvmm_writer.so:system/lib/libnvmm_writer.so \
    vendor/ktouch/w700/proprietary/lib/libnvodm_dtvtuner.so:system/lib/libnvodm_dtvtuner.so \
    vendor/ktouch/w700/proprietary/lib/libnvodm_imager.so:system/lib/libnvodm_imager.so \
    vendor/ktouch/w700/proprietary/lib/libnvodm_query.so:system/lib/libnvodm_query.so \
    vendor/ktouch/w700/proprietary/lib/libnvomxilclient.so:system/lib/libnvomxilclient.so \
    vendor/ktouch/w700/proprietary/lib/libnvomx.so:system/lib/libnvomx.so \
    vendor/ktouch/w700/proprietary/lib/libnvos.so:system/lib/libnvos.so \
    vendor/ktouch/w700/proprietary/lib/libnvrm_channel.so:system/lib/libnvrm_channel.so \
    vendor/ktouch/w700/proprietary/lib/libnvrm_graphics.so:system/lib/libnvrm_graphics.so \
    vendor/ktouch/w700/proprietary/lib/libnvrm.so:system/lib/libnvrm.so \
    vendor/ktouch/w700/proprietary/lib/libnvsm.so:system/lib/libnvsm.so \
    vendor/ktouch/w700/proprietary/lib/libnvtestio.so:system/lib/libnvtestio.so \
    vendor/ktouch/w700/proprietary/lib/libnvtestresults.so:system/lib/libnvtestresults.so \
    vendor/ktouch/w700/proprietary/lib/libnvwinsys.so:system/lib/libnvwinsys.so \
    vendor/ktouch/w700/proprietary/lib/libnvwsi.so:system/lib/libnvwsi.so

# RIL
PRODUCT_COPY_FILES += \
    vendor/ktouch/w700/proprietary/bin/xgold-mux:system/bin/xgold-mux \
    vendor/ktouch/w700/proprietary/bin/rilsyscmd:system/bin/rilsyscmd \
    vendor/ktouch/w700/proprietary/lib/libxgold-ril.so:system/lib/libxgold-ril.so \
    vendor/ktouch/w700/proprietary/lib/libril.so:system/lib/libril.so


